### PR TITLE
Now, if dbt-greenplum failes with dbt 1.1.0

### PR DESCRIPTION
**Pull request by GSokol**
Yes, I know that this will not be used after https://github.com/markporoshin/dbt-greenplum/pull/6 will be merged, but I need it quite ASAP.

### CODE REVIEW

**Comment by markporoshin** [comment]
Hi, give me an hour

**Comment by markporoshin** [comment]
Which version of dbt and dbt-greenplum are you using?

**Comment by markporoshin** [comment]
I build [dbt-greenplum==1.1.0](https://pypi.org/project/dbt-greenplum/)(from #6 ), could you reinstall it and try again?

**Comment by GSokol** [comment]
Yes, that obviously would work with #6.

**Comment by markporoshin** [comment]
Please close pr, if your problem was solved

**Pull request closed without merging**
